baseURL = "https://circuitdiaries.co.uk/"
title = "Circuit Diaries"
languageCode = "en-gb"
theme = "PaperMod"

[pagination]
  pagerSize = 10

[params]
  defaultTheme = "light"          # "light", "dark", or "auto"
  ShowReadingTime = true
  ShowShareButtons = false
  ShowPostNavLinks = true
  ShowBreadCrumbs = true
  ShowCodeCopyButtons = true
  disableSpecial1stPost = true
  mainSections = ["posts"]
  # how many menu items to show in navbar; rest go in "More" menu
  ShowMenuItems = 3

[markup]
  [markup.goldmark]
    [markup.goldmark.renderer]
      unsafe = true

[menu]
  [[menu.main]]
    identifier = "posts"
    name = "Posts"
    url = "/"
    weight = 1

  [[menu.main]]
    identifier = "github"
    name = "GitHub"
    url = "https://github.com/amirfarjam/circuitdiaries"
    weight = 2

  [[menu.main]]
    identifier = "projects"
    name = "Projects"
    url = "https://newfolder22.co.uk/"
    weight = 3

  [[menu.main]]
    identifier = "about"
    name = "About"
    url = "/about/"
    weight = 4
