baseURL = "https://circuitdiaries.co.uk/"
title = "Circuit Diaries"
languageCode = "en-gb"
theme = "PaperMod"

[pagination]
  pagerSize = 10

[params]
  defaultTheme = "light"          # "light", "dark", or "auto"
  ShowReadingTime = true
  ShowShareButtons = false
  ShowPostNavLinks = true
  ShowBreadCrumbs = true
  ShowCodeCopyButtons = true
  disableSpecial1stPost = true
  mainSections = ["posts"]
  # how many menu items to show in navbar; rest go in "More" menu
  ShowMenuItems = 4
  comments = true
  useDescription = true

[params.giscus]
  repo = "amirfarjam/circuitdiaries"
  repoID = "R_kgDOQZM0Aw"
  category = "Comments"
  categoryID = "DIC_kwDOQZM0A84CyAh6"
  mapping = "pathname"
  reactionsEnabled = "1"
  emitMetadata = "0"
  inputPosition = "bottom"
  lang = "en"
  loading = "lazy"

[params.assets]
  favicon = "/favicon.ico"
  favicon16x16 = "/favicon-16x16.png"
  favicon32x32 = "/favicon-32x32.png"
  apple_touch_icon = "/apple-touch-icon.png"

[[params.socialIcons]]
  name = "github"
  url  = "https://github.com/amirfarjam"

[[params.socialIcons]]
  name = "linkedin"
  url  = "https://www.linkedin.com/in/amirfarjamm/"

[[params.socialIcons]]
  name = "email"
  url  = "mailto:info@newfolder22.co.uk"

[markup]
  [markup.goldmark]
    [markup.goldmark.renderer]
      unsafe = true

[menu]
  [[menu.main]]
    identifier = "posts"
    name = "Posts"
    url = "/"
    weight = 1

  [[menu.main]]
    identifier = "github"
    name = "GitHub"
    url = "https://github.com/amirfarjam/circuitdiaries"
    weight = 2

  [[menu.main]]
    identifier = "projects"
    name = "Projects"
    url = "https://newfolder22.co.uk/"
    weight = 3

  [[menu.main]]
    identifier = "about"
    name = "About"
    url = "/about/"
    weight = 4
